### ISSUE TITLE
Resize issue and DPI for high resolutions.

### ISSUE THREAD

**Issue by INTRASERVER** [strimio/strimio-desktop#11]
Hello, thanks for great app. I'm so glad finally I found something what works and playing Latvian radio stations for Windows. But there are some bugs. First of all if you have high resolution monitor or laptop with high resolution screen then by default it looks so small.
Yes it can be fix via change to DPI for compatibility with system.

<img width="1500" alt="Screenshot_20221103_221338" src="https://user-images.githubusercontent.com/97578992/199844878-1fce5e4f-741d-4bd4-bc34-aeb9e4e3ecb5.png">

Photo two shows how it looks if you change settings:

<img width="1500" alt="Screenshot_20221103_221148" src="https://user-images.githubusercontent.com/97578992/199845049-f164bf09-e190-4f5e-aa65-14d7e9cbe422.png">

Second issue is resize back to normal size. If you maximaze the it not resize back to normal size.

<img width="1500" alt="Screenshot_20221103_222202" src="https://user-images.githubusercontent.com/97578992/199845629-598d1a46-cb24-484b-a505-9fc51f5c10a0.png">

**Comment by spiral2k** [comment]
Hey @INTRASERVER, thank you for the feedback. I appreciate it.

Please correct me if I've misunderstood. There are two issues here. One with the DPI, which should automatically be set depending on the resolution, and the second issue is with the maximize/minimize functionality, am I correct?

Regarding the icon, Strimio's icon should look like this, maybe the windows settings can help?
![image](https://user-images.githubusercontent.com/3942027/199862308-51f83fe1-64a7-4450-b45e-8614969b6cca.png)

**Comment by INTRASERVER** [comment]
Hello, yes first issue is with DPI which should be set depending on the resolution. As you see with my resolution by default app looks so small. And I change DPI using method from first photo. After changed DPI it looks normal it is photo two. Second issue is maximize. When you maximaze, you can't unmaximize.

I know it looks like this way icon but I'll be glad you add rounded icon. I changed to rounded icon.

**Comment by spiral2k** [comment]
@INTRASERVER  thanks I'm looking into both issues.

regarding the icon, I'll check if I can create an "icon chooser" setting.

**Comment by spiral2k** [comment]
@INTRASERVER version 3.0.10 should fix the unmaximize issue

**Comment by INTRASERVER** [comment]
Resize works now, thanks. But I have two more things what I'd like to see added in application. One thing is player buttons in the taskbar preview windows.

<img width="214" alt="Screenshot_20221105_210018" src="https://user-images.githubusercontent.com/97578992/200141384-71e447d3-614b-4853-a5ec-1d3167aea752.png"> 

And second is windows shadow. If you see strimio as hasn't shadow but other player has shadow and looks more beutiful more like windows 10/11 UI. I like blur background looks awesome but shadow will make it more better.

**Comment by LSeelig** [comment]
Am also having DPI and scaling issues on second monitor (Windows).

**Comment by LSeelig** [comment]
The icon still appears very blurry on Windows. I checked in Resource hacker, and there is a high-res file, but it isn't being used by Windows.  
The application window seems highly irregular. The minimize button is different from most other native apps, and it doesn't work with tiling in addition to minimize and DPI issues. Strangely, the window also lacks the typical dropshadow. I will note the other electron apps I have don't share any of these issues. I can send screenshots if you would like, but these problems are kinda hard to show without motion. However the app displays itself in Windows seems to cause a lot of issues.

**Comment by spiral2k** [comment]
Hey @LSeelig,saw your screenshot, it looks bad indeed. I'll attempt to fix these issues inthe coming weeks (I'm installing windows for this -_-)

can you send me a screenshot of the minimize behavior and the DPI issue? it will help me understand the issues better

Thank you for making strimio better!
I will keep you posted

**Comment by LSeelig** [comment]
Thank you. I understand this is a personal project, so I have no expectations of you. I will do what I can to help however. It seems to me that windows does not see this as a regular application window at all. It reminds me of some programs like overlays that are not meant to display as windows.
List:
No hover charm to tile window
Button shape - minimize button shape wrong
Missing system animations - minimize, close, maximize and restore
Scaling
Icon

![Drop Shadow](https://user-images.githubusercontent.com/37001137/230220030-aee22390-fa35-4df2-a24a-7243bc99343a.png)
![Tile Manager (expected behavior](https://user-images.githubusercontent.com/37001137/230220031-88c5977e-327d-4ba1-8999-22e7e95d8528.png)
![Window Controls](https://user-images.githubusercontent.com/37001137/230220032-83505884-a53e-4840-82fb-b55385e4edbe.png)

https://user-images.githubusercontent.com/37001137/230220647-a9c8eaed-38af-49f5-87a5-3292e30c8f8f.mp4

https://user-images.githubusercontent.com/37001137/230221026-92f6ef13-fcdf-408b-a7ae-d06f924b9327.mp4
